### PR TITLE
Version 1.3 update

### PR DESCRIPTION
**Pull request by thehappydinoa**
Fixed Styling
Fixed GET TARGET_OS error (#280)
Removed language=''

### CODE REVIEW

**Comment by B0rk** [comment]
Aidan, quit fucking with my scripts...

-B0rk

**Comment by thehappydinoa** [comment]
@B0rk Sorry

**Comment by B0rk** [comment]
I apologize for being so gruff about it, but I'd appreciate if you made
suggestions for changes/modifications on the thread for my payload in the
forums and make a request before modifying. That being said, I would like
to thank you for updating it for newer FW, and again, I apologize for my
earlier frustration.

-B0rk

**Comment by thehappydinoa** [comment]
@B0rk I am appologize I did not see that part of your README.md, that is 100% my bad. If there is anything you need lmk

**Pull request closed without merging**
