### PR TITLE
Extension SEWAIT - Social Engineering WAIT

### PR DESCRIPTION
**Pull request by GermanNoob**
a small extension to DarrenKitchen's wait.sh

If you have to social engineer your way to the target... This extension will mount as storage and wait for the user to start the real payload by changing switch position.

Be aware, that if your real payload utilizes "switch position" command within itself you should call it BEFORE calling SEWAIT

### CODE REVIEW

**Comment by NickRaw** [comment]
If you look into my payload you will see that I have done that. In the first stage of my payload I get the SWITCH_POSITION and I put it in a variable called PRIMARYSTH. Now every time I want to use my actual switch position I called the variable PRIMARYSTH instead of SWITCH_POSITION

**Comment by thehappydinoa** [comment]
Ya this is a great idea. Do you think you could make some changes to make it appear as a blank hard drive named untitled?

**Comment by GermanNoob** [comment]
I would like to do that, but unfortunately I think this would be a feature which has to be done by Hak5. Something like "ATTACKMODE SE_STORAGE" which mounts a unsuspicious partition. But maybe it is possible just to rename the BashBunny to something more common?

**Comment by NickRaw** [comment]
Best way to use WAIT and utilize the SWITCH_POSITION is to get the switch position first and put it into a different variable. Then every time you want to get the switch position of the actual switch you call the variable you made before.

**Comment by thehappydinoa** [comment]
Ya that would be a great feature to see @sebkinne

**Comment by GermanNoob** [comment]
Messed up my branches... Sorry, will do a new one with only SEWAIT and separately iMessageGrabber

**Pull request closed without merging**
