### PR TITLE
Execution - Get System Account

### PR DESCRIPTION
**Pull request by TW-D**
Spoofing "NT AUTHORITY\SYSTEM" via parent process using PowerShell and embedded C Sharp.
Avoid PowerShell logging.
Use 'PowerShdll' for AppLocker Bypass.

### CODE REVIEW

**Comment by foxtrot** [comment]
https://github.com/p3nt4/PowerShdll

**Comment by Atmosphere9999** [comment]
### _Hello everyone!_ 

### I am Austin Spraggins or AgtShadow on Kali Linux or Shadow Gaming™ LLC on YouTube.

**And to @TW-D, thank you so much for working on these new outstanding, exceptional, necessitated recent/contemporary, and more modern and updated Payloads since most of these payloads are four years or older.**

Ever since the Bash Bunny Mark II has been in my possession for the past two weeks or whenever it was first released, I am still experimenting with it and writing automation payloads for it. I am now eager, inquisitive, and ready to write some malicious payloads now. 

I would like to contribute to finishing this payload with you and whoever else. 

I also work as a Frontend Web Designer/Developer AND Offensive Cybersecurity Pentester at my College, so I have over 600 laptops here and about 100 I can test these payloads out on, and I do with authorized permission. 

We are also looking to write payloads for imaging post-configuration. Possibly be able to push that script onto the Windows Server so the script/payload can be made onto as many computers as possible at the same time. 

Anyway, if anyone needs a payload tested, go ahead and shoot me an email or comment back. I will help and experiment and test it when I have the time. 

I have full authorized access to Windows 7, 8, 10, and Windows 11 Insider Build and Mac OS Catalina and Big Sur (whatever the newest update is called) or any OS I have on VMware Workstation Pro 16, which is just about all of them.

And I spend 99.99% of the time on Kali Linux only or VS Code for Web Development using Vue, React, HTML5/CSS3 & SASS, and of course, good old JavaScript. 

All Of My Contact Information is on my Portfolio & Resume webpage, which I ironically need help with, please: https://www.austinspragginsportfolio.xyz/

`
                _    _____ _               _               
     /\        | |  / ____| |             | |              
    /  \   __ _| |_| (___ | |__   __ _  __| | _____      __
   / /\ \ / _` | __|\___ \| '_ \ / _` |/ _` |/ _ \ \ /\ / /
  / ____ \ (_| | |_ ____) | | | | (_| | (_| | (_) \ V  V / 
 /_/    \_\__, |\__|_____/|_| |_|\__,_|\__,_|\___/ \_/\_/  
           __/ |                                           
          |___/                                            
`

**Comment by TW-D** [comment]
Thank you for your encouragement.

**Comment by TW-D** [comment]
Closing because new version is faster and without 'PowerShdll'.

**Pull request closed without merging**
