### PR TITLE
Config Payloads to run off of a Config file

### PR DESCRIPTION
**Pull request by mrt0mat0**
Instead of copying files back and forth into switches, why not use this handy dandy config.txt file. create as many new library resources as you'd like. Makes swapping out payloads a breeze!

### CODE REVIEW

**Comment by hink** [comment]
This sounds somewhat problematic as payloads are generally customized per engagement.

**Comment by mrt0mat0** [comment]
How does that make it problematic?

**Comment by hink** [comment]
In a scenario where library serves as 'templates' I may have 3 or 4 running configurations of a particular payload for an engagement. Think SMB Exfil payload.

One engagement, I may need to modify the powershell to bypass AV, or grab different files. Your mileage may vary.

I see library as being a mirror of the git repo.

**Comment by mrt0mat0** [comment]
So, what I did is creat a "custom" folder inside payloads. Problem solved.
Now I can not only use those libraries and not modify them, but quickly
save and reuse my own. No worry about overwriting a modification in switch1.

**Comment by mrt0mat0** [comment]
If there are any other concerns, please feel free to ask about them. I'm actually parlaying this change into a bigger and more amazing modification to the functionality of the bash bunny that I think everyone will love! But, until I can guarantee it will work, i'm keeping it a secret!

**Pull request closed without merging**
