### PR TITLE
OSXUTILS: An extension for HID attacks on OSX 

### PR DESCRIPTION
**Pull request by bobmcdouble3**
Added OSXUTILS, an extension that gives shortcuts for HID attacks on OSX

### CODE REVIEW

**Comment by bobmcdouble3** [comment]
Sorry for the old commits, my mistake :)

**Comment by quentinlamamy** [comment]
seems we work on the same area :)
[https://github.com/hak5/bashbunny-payloads/pull/239](url)

**Comment by bobmcdouble3** [comment]
Took a little inspiration from you @quentinlamamy do you want me to credit you if I push another update?

**Comment by bobmcdouble3** [comment]
wait sorry wrong person lol

**Comment by bobmcdouble3** [comment]
did not even know yours existed! Sorry! I took inspiration from a Windows one sort of like this @quentinlamamy

**Comment by quentinlamamy** [comment]
@bobmcdouble3 Goal is to give access to all specific osx tool more or less hidden like cafeinate and all api behind apple script

**Pull request closed without merging**
