### PR TITLE
Funny Notepad Prank

### PR DESCRIPTION
**Pull request by The10FpsGuy**
This is just for fun :D

### CODE REVIEW

**Comment by The10FpsGuy** [comment]
I am preeetty new to this kinda scripting language so i dont know how to do that. And i just wanted it to be Fun :D

**Comment by mrhut10** [comment]
hopefully i'm not touching the fun aspec? i'm newish as well.

*added a small delay encase notepad opens a little slower than expected
*added a header option, (as well as your original footer message)
*body of message uses a loop so you can quickly configure how many lines of it you like.

[payload.txt](https://github.com/hak5/bashbunny-payloads/files/880631/payload.txt)

hopefully helpful, regards from fairly green bash'er as well.

**Comment by mrhut10** [comment]
oh BTW i'm new to git, I've attached that change in that previous comment.
however no doubt thats not how your meat to use git when recomending a change however i have no idea how to submit :)
your welcome to use it how you see fit.

**Comment by mrhut10** [comment]
lol meat

**Comment by The10FpsGuy** [comment]
Thank u :D

**Comment by Biocow** [comment]
I made a few changes so that the script uses external files rather than variables for the injection. This makes it easier since each line doesn't need to start with QUACK (or Q) and it is easier to make larger attack files. (See body2.txt and change the payload.txt line to use it to see it in action.)

[body.txt](https://github.com/hak5/bashbunny-payloads/files/888592/body.txt)
[body2.txt](https://github.com/hak5/bashbunny-payloads/files/888595/body2.txt)
[footer.txt](https://github.com/hak5/bashbunny-payloads/files/888596/footer.txt)
[header.txt](https://github.com/hak5/bashbunny-payloads/files/888594/header.txt)
[payload.txt](https://github.com/hak5/bashbunny-payloads/files/888593/payload.txt)

**Pull request merged**
