### PR TITLE
Windows bind and reverse VNC

### PR DESCRIPTION
**Pull request by El3ct71k**
New VNC payload

### CODE REVIEW

**Comment by sebkinne** [comment]
Hi @El3ct71k - would you mind re-submitting this PR with just the new payload?

**Comment by El3ct71k** [comment]
Hey Sebastian, sorry but I don’t understand what you mean, can you clarify
you request please?

**Comment by sebkinne** [comment]
@El3ct71k - this PR contains the VNC payload, and changes to the recently removed Mr Robot payload.

If possible, please re-submit this PR, only including the VNC payload.

**Comment by El3ct71k** [comment]
Sure! I’ll do that tommorow.. now is night in my country. Thanks for your
explanation ! I’ll send a new pull request tommorow

**Comment by El3ct71k** [comment]
Hi Sebastian, i make a new PR as you asked me. the URL is:
https://github.com/hak5/bashbunny-payloads/pull/295

Waiting for your response :)
Nimrod.

**Pull request closed without merging**
