### PR TITLE
[PAYLOAD] Bunny-Flip

### PR DESCRIPTION
**Pull request by hkyq**
Hi, I'd like to submit my simple but effective payload that flips the users screen around. 

:)

### CODE REVIEW

**Comment by TheRealNoob** [comment]
Payloads aren't approved without readme files.  Just create a new file named readme.md and put your stuff in there.  If you need help with the syntax google "github readme.md".

If you haven't already you will need to put the payload and readme in their own folder.

**Comment by hkyq** [comment]
Okay, thanks @TheRealNoob. How do I add another file to the pull request?

**Comment by TheRealNoob** [comment]
it looks like you made the pull request against a branch named "patch-1".  You will need to add your files to that branch in order to see them reflected here.

It is possible to change the HEAD branch on this pull request, but I've been told by others (who really know how to use Git) that in situations like these it's not worth the effort.  It would be easier to just recreate the pull request against the master branch.

**Comment by hkyq** [comment]
Alright, I'll try.

**Pull request closed without merging**
