### PR TITLE
actually giving TARGET_OS a value

### PR DESCRIPTION
**Pull request by TheDragonkeeper**
Wouldn't it be better to give TARGET_OS a value other than always exporting it as 'UNKNOWN'

### CODE REVIEW

**Comment by thehappydinoa** [comment]
That would be preferable. I apologize that was my bad.

**Comment by sundhaug92** [comment]
Yup. Looks like we missed that one in #277. @sebkinne, could we fast-track this?

**Comment by sebkinne** [comment]
Thanks for this - can't believe I missed that :)

**Comment by thehappydinoa** [comment]
@sebkinne me neither I don't know how I messed that up.

**Pull request merged**
