### PR TITLE
Add bunny-connecter.sh

### PR DESCRIPTION
**Pull request by rsxchin**
1. Moves bunny-connecter.sh configs to bunny_connecter_config.txt 
2. Add bunny_connecter_config.txt to gitignore so user changes won't be pushed

The modified version adds specific iptables rules rather than flushing them altogether.

If bunny_connecter_config.txt doesn't exist in the same directory, it will be created.

### CODE REVIEW

**Comment by rsxchin** [comment]
resolves #117

**Comment by rsxchin** [comment]
@hak5glytch, is there anything you need me to change?

**Comment by hak5darren** [comment]
@rsxchin do you mind submitting this as a separate version of the bb.sh file (named however you wish)? Thanks!

**Comment by rsxchin** [comment]
Renamed and updated

**Comment by rsxchin** [comment]
@hak5darren, are there any other changes you want?

**Comment by rsxchin** [comment]
Did I do something wrong?

**Pull request merged**
