### PR TITLE
Violation of CoC

### PR DESCRIPTION
**Pull request by xillwillx**
Removing my code from repo due to Violation of CoC demands

### CODE REVIEW

**Comment by sebkinne** [comment]
HI @xillwillx - what do you mean with Violation of CoC?

**Comment by xillwillx** [comment]
Greets sebkinne, just wanted to pull my code, because I don't conform with the CoC snubs is pushing as a demand for all conferences that support Hak5. So respectfully to your hard work on making some great hardware devices, I no longer want to contribute my code to the repo.

**Comment by sebkinne** [comment]
@xillwillx understood. As this PR just adds the RandomRoll payload now, I'll close this.

**Comment by xillwillx** [comment]
My repo was out of date from 7 months ago, could you just remove these payloads:
**Credentials:**
BrowserCreds, JackRabbit, MrRobot, WiFiCreds 
**Prank:**
RickRoll
**Recon:** 
PrivEscChecker

**Pull request closed without merging**
