### PR TITLE
An extension to overwrite the default keyboard layout to en-US

### PR DESCRIPTION
**Pull request by elkentaro**
This extension will allow the overwriting of the default input keyboard layout to en-US for easier execution of some of the Quack commands.  Its an alternative means to use the Ducky scripts for cases where you know the target environment but do not have the capabilities to generate a [language].json file.

### CODE REVIEW

**Comment by sebkinne** [comment]
@elkentaro this looks great, thanks! 

The only problem I have with this is that it will leave the language on en-US after it is done running. It would be great if the Powershell command could memorize the current keyboard language and then allow the user to restore that once they are done with their payload.

If you don't mind also putting a little bit more detail (why is this command needed?) into the description in the file that would be great.

**Comment by elkentaro** [comment]
Oh yea I see what you mean, I just wrote it as a generic overwrite , but yea will do.

**Comment by sebkinne** [comment]
@elkentaro I'll wait with the merge then :)

**Comment by elkentaro** [comment]
My bad, I just found out that "-" is mapped different on some Western language keyboards, could cause some problems.

**Comment by elkentaro** [comment]
Nevermind, found a workaround , changing the key code for "-" to "00:00:56" (i.e.:keypad - ) makes the extension universal.

**Comment by 0xCoto** [comment]
Amazing work! :)

**Comment by sebkinne** [comment]
I see what you mean with the `-` character. Having to modify the default us.json is however a pain for the user. Instead of rolling the change into the firwmare, maybe it makes sense to add some kind of escape code that the QUACK command will understand. That way, you could directly send 00:00:56.

I'll have a play with it and keep you updated, but I'm thinking of something along the lines of `QUACK LITERAL 00:00:56`. Any thoughts on this would be appreciated.

**Comment by sebkinne** [comment]
That was way easier than I expected. In FW v1.2 we'll have `QUACK KEYCODE 00,00,56`. Once we push the new firmware I'll make sure the extension is updated.

**Comment by elkentaro** [comment]
Cool . Although one more thing , maybe not for the next firmware version but down the road eventually. Even with the KEYCODE option it will still only send out keys defined within a regular en-US keyboard, but none of the Volume Up and other media keys etc etc. I can see people complaining that QUACK KEYCODE doesn't work, because they are trying to send a key code higher that the "Logical Maximum" in the HID descriptor. We probably should increase this value to allow for higher KEYSTROKE values. like the media keys, ¥ (yen mark) etc etc.

**Pull request merged**
