### PR TITLE
DumpCreds New Version 2.2 

### PR DESCRIPTION
**Pull request by qdba**
## Changelog

Version 2.2
- smbserver stuff removed
- handshake removed
- HTTP Server added (Download Powershell scripts, upload loot)
- Invoke-m1m1d0gz.ps1 AES encrypted to Invoke-M1m1d0gz.enc. 
     Not really neccessary but if you are in storage mode, the AV doesn't remove it. :-)
- All in all a little bit faster
- remove the debug code
- recoded the Get-WiFiCreds.ps1 for working on Windows 7

### CODE REVIEW

**Comment by qdba** [comment]
Build 1007 Fixed some Errors with Char Encoding during Net.Webclient .downloadstring

**Comment by mubix** [comment]
Can you remove the commit for deleting the .gitignore

**Comment by qdba** [comment]
I Closed the Pull request because of confused last commit.

**Comment by qdba** [comment]
Because of a mismatch of commits I delete the pull request #192 rebased my fork and create a new pull request #247 with 

DumpCreds Version 2.3 



Greez

DIeter Baur 



-----Ursprüngliche Nachricht-----
Von: Rob Fuller <notifications@github.com>
Gesendet: Dienstag 12 September 2017 17:26
An: hak5/bashbunny-payloads <bashbunny-payloads@noreply.github.com>
CC: Dieter Baur <dieter@baur.nu>; Author <author@noreply.github.com>
Betreff: Re: [hak5/bashbunny-payloads] DumpCreds New Version 2.2 (#192)

Can you remove the commit for deleting the .gitignore

**Pull request closed without merging**
