### PR TITLE
Adding captive portals from my travels: https://github.com/securesean…

### PR DESCRIPTION
**Pull request by securesean**
I don't know if this is the best place for them

### CODE REVIEW

**Comment by TorreyBetts** [comment]
For legal reasons you may have to remove location names and graphics associated with those places.

**Comment by rastating** [comment]
> For legal reasons you may have to remove location names and graphics associated with those places.

I was thinking the same

**Comment by sebkinne** [comment]
I don't think such a large library belongs into the payload - I would suggest putting this on the forums.

**Comment by securesean** [comment]
Roger

**Pull request closed without merging**
